seed:
  min: 0
  max: 10
fold:
  min: 0
  max: 5
model:
  -
    model_name: SHRED-I
    model_params:
      hidden_size: 32
      emb_size: 32
      clf_hidden_1: 0
      clf_hidden_2: 0
      dropout: 0.2
    hyperparameters:
      rc_loss: 0.0001
      kl_loss: 0.001
      ch_loss: 1.0
      alpha_loss: true
    optim_params:
      lr: 0.002
      l2_reg: 0.001
data:
  -
    output_directory: ../.archive/Schiz_WHOLE
    dataset: Schiz
    labeled_sites:
      - 
        - h
        - nmorph
        - ucla
        - cobre
experiment_settings:
  -
    ssl: false
    harmonize: false
    validation: false
process:
  device: 3
  verbose: false
  max_epoch: 1000
  patience: 1000
  save_model_condition:
    -
      dataset: Schiz