seed:
  min: 0
  max: 10
fold:
  min: 0
  max: 5
model:
  -
    model_name: VAE-FFN
    model_params:
      hidden_size: 32
      emb_size: 16
      clf_hidden_1: 0
      clf_hidden_2: 0
      dropout: 0.1
    hyperparameters:
      rc_loss: 0.0001
      kl_loss: 0.001
    optim_params:
      lr: 0.001
      l2_reg: 0.001
data:
  -
    output_directory: ../.archive/Schiz_WHOLE
    dataset: Schiz
    labeled_sites:
      - 
        - h
        - nmorph
        - ucla
        - cobre
experiment_settings:
  -
    ssl: false
    harmonize: false
    validation: false
  -
    ssl: false
    harmonize: true
    validation: false
process:
  device: 3
  verbose: false
  max_epoch: 1000
  patience: 1000
  save_model_condition:
    -
      dataset: Schiz
