seed:
  min: 10
  max: 11
fold:
  min: 0
  max: 5
model:
  -
    model_name: SHRED-I
    model_params:
      hidden_size: 64
      emb_size: 16
      clf_hidden_1: 0
      clf_hidden_2: 0
      dropout: 0.1
    hyperparameters:
      rc_loss: 0.00001
      kl_loss: 0.001
      ch_loss: 0.01
      alpha_loss: true
    optim_params:
      lr: 0.0005
      l2_reg: 0.001
data:
  -
    output_directory: ../.archive/Schiz_INDIVIDUAL
    dataset: Schiz
    labeled_sites:
      - h
      - nmorph
      - ucla
      - cobre
experiment_settings:
  -
    ssl: true
    harmonize: false
    validation: false
process:
  device: 0
  verbose: false
  max_epoch: 1000
  patience: 1000
  save_model_condition:
    -
      dataset: Schiz
